version: 1 
runtime: python27
api_version: 1 
threadsafe: true
application: musicmanager

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
- url: /templates
  static_dir: templates
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /api
  static_dir: api/
